// Catálogo de filtros de CLIENTES (generado desde el WSDL; editable).
// Mismos campos que filtros.config.js de artículos. Ver esa doc.
export const CATALOGO_CLIENTES = [
  { atributo: "ClienteID", label: "ID", tipo: "int", opciones: "texto", columna: true, habilitado: true },
  { atributo: "Nombre", label: "Nombre", tipo: "string", opciones: "texto", columna: true, habilitado: true },
  { atributo: "NombreLegal", label: "Nombre legal", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EsClienteGlobal", label: "Es cliente global", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Domicilio", label: "Domicilio", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Localidad", label: "Localidad", tipo: "string", opciones: "texto", columna: true, habilitado: true },
  { atributo: "CodigoPostal", label: "Codigo postal", tipo: "int", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Provincia", label: "Provincia", tipo: "string", opciones: "lista", nombreAttr: "ProvinciaNombre", columna: true, habilitado: true },
  { atributo: "Pais", label: "Pais", tipo: "string", opciones: "lista", nombreAttr: "PaisNombre", columna: true, habilitado: false },
  { atributo: "Telefono", label: "Telefono", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Fax", label: "Fax", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Email", label: "Email", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Observacion", label: "Observacion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CodigoDeProveedorParaElCliente", label: "Codigo de proveedor para el cliente", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Referencia", label: "Referencia", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "HorarioDeAtencion", label: "Horario de atencion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "HorarioDeEntrega", label: "Horario de entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CondicionAnteElIVA", label: "Condición IVA", tipo: "string", opciones: "lista", nombreAttr: "CondicionAnteElIVANombre", columna: true, habilitado: true },
  { atributo: "ClaveTributaria", label: "Clave tributaria", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "IngresosBrutos", label: "Ingresos brutos", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ContactoDeVenta", label: "Contacto de venta", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ContactoDeCobros", label: "Contacto de cobros", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CondicionPago", label: "Condicion pago", tipo: "string", opciones: "lista", nombreAttr: "CondicionPagoNombre", columna: true, habilitado: false },
  { atributo: "MonedaUsualCuentaCorriente", label: "Moneda usual cuenta corriente", tipo: "string", opciones: "lista", nombreAttr: "MonedaUsualCuentaCorrienteNombre", columna: true, habilitado: false },
  { atributo: "CuentaCliente", label: "Cuenta cliente", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "TipoDeCliente", label: "Tipo de cliente", tipo: "string", opciones: "lista", nombreAttr: "TipoDeClienteNombre", columna: true, habilitado: true },
  { atributo: "ActividadDeCliente", label: "Actividad de cliente", tipo: "string", opciones: "lista", nombreAttr: "ActividadDeClienteNombre", columna: true, habilitado: false },
  { atributo: "Clasificacion1", label: "Clasificacion 1 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion1Nombre", columna: true, habilitado: false },
  { atributo: "Clasificacion2", label: "Clasificacion 2 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion2Nombre", columna: true, habilitado: false },
  { atributo: "Clasificacion3", label: "Clasificacion 3 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion3Nombre", columna: true, habilitado: false },
  { atributo: "Clasificacion4", label: "Clasificacion 4 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion4Nombre", columna: true, habilitado: false },
  { atributo: "Clasificacion5", label: "Clasificacion 5 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion5Nombre", columna: true, habilitado: false },
  { atributo: "Clasificacion6", label: "Clasificacion 6 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion6Nombre", columna: true, habilitado: false },
  { atributo: "Clasificacion7", label: "Clasificacion 7 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion7Nombre", columna: true, habilitado: false },
  { atributo: "Clasificacion8", label: "Clasificacion 8 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion8Nombre", columna: true, habilitado: false },
  { atributo: "Clasificacion9", label: "Clasificacion 9 (cliente)", tipo: "string", opciones: "lista", nombreAttr: "Clasificacion9Nombre", columna: true, habilitado: false },
  { atributo: "Vendedor", label: "Vendedor", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ZonaDeVenta", label: "Zona de venta", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Cobrador", label: "Cobrador", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Transporte", label: "Transporte", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "BloqueadoParaNotasDePedido", label: "Bloqueado para notas de pedido", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "BloqueadoParaFacturar", label: "Bloqueado para facturar", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FechaDeAlta", label: "Fecha de alta", tipo: "date", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FechaDeBaja", label: "Fecha de baja", tipo: "date", opciones: "texto", columna: true, habilitado: false },
  { atributo: "HabilitadoParaConsultasWeb", label: "Habilitado para consultas web", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FormatoDeImpresionPorCliente", label: "Formato de impresion por cliente", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Vendedor2", label: "Vendedor 2", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AtributoString1", label: "Atributo string 1", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AtributoString2", label: "Atributo string 2", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AtributoString3", label: "Atributo string 3", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AtributoString4", label: "Atributo string 4", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AtributoFecha1", label: "Atributo fecha 1", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AtributoFecha2", label: "Atributo fecha 2", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AtributoFecha3", label: "Atributo fecha 3", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AtributoFecha4", label: "Atributo fecha 4", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion1PedidosYComprobantesVarios", label: "Clasificacion 1 pedidos ycomprobantes varios", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion2PedidosYComprobantesVarios", label: "Clasificacion 2 pedidos ycomprobantes varios", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion3PedidosYComprobantesVarios", label: "Clasificacion 3 pedidos ycomprobantes varios", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion4PedidosYComprobantesVarios", label: "Clasificacion 4 pedidos ycomprobantes varios", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion5PedidosYComprobantesVarios", label: "Clasificacion 5 pedidos ycomprobantes varios", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion6PedidosYComprobantesVarios", label: "Clasificacion 6 pedidos ycomprobantes varios", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "HabilitadoParaConciliacionConEmpresaCliente", label: "Habilitado para conciliacion con empresa cliente", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CodigoDeClienteExterno", label: "Codigo de cliente externo", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FechaDeProximaGestionDeCobranza", label: "Fecha de proxima gestion de cobranza", tipo: "date", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ProximaGestionDeCobranza", label: "Proxima gestion de cobranza", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FormaDeGenerarComprobantesEnElSistemaDeContratos", label: "Forma de generar comprobantes en el sistema de contratos", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "NodoOrigen", label: "Nodo origen", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Municipio", label: "Municipio", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "SeConsideraParaTasaDeAbasto", label: "Se considera para tasa de abasto", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ControlaElCobroCorrelativoPorVencimiento", label: "Controla el cobro correlativo por vencimiento", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "VehiculoPorDefecto", label: "Vehiculo por defecto", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Distribuidor", label: "Distribuidor", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ZonaDeDistribucion", label: "Zona de distribucion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Calle", label: "Calle", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "NumeroCalle", label: "Numero calle", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Piso", label: "Piso", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Departamento", label: "Departamento", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Barrio", label: "Barrio", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "DiasDeGraciaParaElCalculoDeDiasDeAtrasoDeRecibos", label: "Dias de gracia para el calculo de dias de atraso de recibos", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "SitioWeb", label: "Sitio web", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "DescripcionDeLaActividad", label: "Descripcion de la actividad", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FacturacionAnualEnMonedaLocal", label: "Facturacion anual en moneda local", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CantidadDeEmpleados", label: "Cantidad de empleados", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EnvioComprobantesPorMailDireccionDeMail", label: "Envio comprobantes por mail direccion de mail", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EnvioComprobantesPorMailAsuntoDelMail", label: "Envio comprobantes por mail asunto del mail", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EnvioComprobantesPorMailCuerpoDelMail", label: "Envio comprobantes por mail cuerpo del mail", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ObservacionDeProximaGestionDeCobranza", label: "Observacion de proxima gestion de cobranza", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CodigoDeCalle", label: "Codigo de calle", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EnvioRecibosDeClientesPorMailDireccionDeMail", label: "Envio recibos de clientes por mail direccion de mail", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EnvioRecibosDeClientesPorMailAsuntosDelMail", label: "Envio recibos de clientes por mail asuntos del mail", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EnvioRecibosDeClientesPorMailCuerpoDelMail", label: "Envio recibos de clientes por mail cuerpo del mail", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "TasaMensualParaCalculoDeInteres", label: "Tasa mensual para calculo de interes", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EmailBackup", label: "Email backup", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "NovedadFecha", label: "Novedad fecha", tipo: "string", opciones: "texto", columna: false, habilitado: false },
  { atributo: "BloqueadoReservas", label: "Bloqueado reservas", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "PersFisTipoDeDocumento", label: "Pers fis tipo de documento", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "PersFisNumeroDeDocumento", label: "Pers fis numero de documento", tipo: "string", opciones: "texto", columna: true, habilitado: false },];
