// Catálogo de filtros de PEDIDOS (notas de pedido). Generado desde el WSDL.
// opciones "texto" en todos: la consulta del ERP es lenta para derivar valores.
export const CATALOGO_PEDIDOS = [
  { atributo: "Division", label: "Division", tipo: "int", opciones: "texto", columna: true, habilitado: true },
  { atributo: "Tipo", label: "Tipo", tipo: "string", opciones: "texto", columna: true, habilitado: true },
  { atributo: "Numero", label: "Numero", tipo: "int", opciones: "texto", columna: true, habilitado: true },
  { atributo: "FechaDeEmision", label: "Fecha de emision", tipo: "date", opciones: "texto", columna: true, habilitado: true },
  { atributo: "Cliente", label: "Cliente", tipo: "int", opciones: "texto", columna: true, habilitado: true },
  { atributo: "Moneda", label: "Moneda", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CondicionDePago", label: "Condicion de pago", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Referencia", label: "Referencia", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Observacion", label: "Observacion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ListaDePrecioDeVenta", label: "Lista de precio de venta", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CantidadDeDescuentosDeCabecera", label: "Cantidad de descuentos de cabecera", tipo: "decimal", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CantidadDedescuentosDeRenglones", label: "Cantidad dedescuentos de renglones", tipo: "decimal", opciones: "texto", columna: true, habilitado: false },
  { atributo: "DescuentoNetoOBrutoDeCabecera", label: "Descuento neto obruto de cabecera", tipo: "decimal", opciones: "texto", columna: true, habilitado: false },
  { atributo: "DescuentoNetoOBrutoDeRenglones", label: "Descuento neto obruto de renglones", tipo: "decimal", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FechaDeAlta", label: "Fecha de alta", tipo: "date", opciones: "texto", columna: true, habilitado: false },
  { atributo: "DireccionDeEntregaCliente", label: "Direccion de entrega cliente", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "DireccionDeEntregaClienteRenglon", label: "Direccion de entrega cliente renglon", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Transporte", label: "Transporte", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EsFacturable", label: "Es facturable", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "DiscriminaImpuestos", label: "Discrimina impuestos", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ImporteBrutoMonedaOrigen", label: "Importe bruto moneda origen", tipo: "decimal", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ImporteTotalMonedaOrigen", label: "Importe total moneda origen", tipo: "decimal", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EstadoDeAprobacion", label: "Estado de aprobacion", tipo: "boolean", opciones: "texto", columna: true, habilitado: true },
  { atributo: "FechaDeAprobacion", label: "Fecha de aprobacion", tipo: "date", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AprobacionAutomatica", label: "Aprobacion automatica", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CausaEstadoAprobacion", label: "Causa estado aprobacion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "UsuarioAutorizacionManualOBatch", label: "Usuario autorizacion manual obatch", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ObservacionEstadoAprobacion", label: "Observacion estado aprobacion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "PorcentajeDeDesvioMaximoExcesoEnEntrega", label: "Porcentaje de desvio maximo exceso en entrega", tipo: "decimal", opciones: "texto", columna: true, habilitado: false },
  { atributo: "IndicadorDeDeposito", label: "Indicador de deposito", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "DepositoBaseDeConfeccion", label: "Deposito base de confeccion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FechaDeEntregaBase", label: "Fecha de entrega base", tipo: "date", opciones: "texto", columna: true, habilitado: false },
  { atributo: "FechaDeUltimaImpresion", label: "Fecha de ultima impresion", tipo: "date", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion1Pedido", label: "Clasificacion 1 (pedido)", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion2Pedido", label: "Clasificacion 2 (pedido)", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion3Pedido", label: "Clasificacion 3 (pedido)", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion4Pedido", label: "Clasificacion 4 (pedido)", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion5Pedido", label: "Clasificacion 5 (pedido)", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Clasificacion6Pedido", label: "Clasificacion 6 (pedido)", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ExigeReservaDeStockParaRemitir", label: "Exige reserva de stock para remitir", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "RequiereFacturaDeAnticipo", label: "Requiere factura de anticipo", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "PreciosIncluyenImpuestos", label: "Precios incluyen impuestos", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "TasaDePreciosConImpuestos", label: "Tasa de precios con impuestos", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "CalculaYGrabaImpuestosPorItem", label: "Calcula ygraba impuestos por item", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "HorarioDeEntrega", label: "Horario de entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "PermiteReservarSinAprobacion", label: "Permite reservar sin aprobacion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Vehiculo", label: "Vehiculo", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "Distribuidor", label: "Distribuidor", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "HabilitadoParaVentaDeCereal", label: "Habilitado para venta de cereal", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "IngresaArticulosPorTalleYColor", label: "Ingresa articulos por talle ycolor", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "EsPedidoDeEntregaDeAcopio", label: "Es pedido de entrega de acopio", tipo: "boolean", opciones: "texto", columna: true, habilitado: false },
  { atributo: "NumeroInternoDePedidoDeAcopio", label: "Numero interno de pedido de acopio", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "AplicaDescuentoPorMonto", label: "Aplica descuento por monto", tipo: "decimal", opciones: "texto", columna: true, habilitado: false },
  { atributo: "VolumenEmbaladoCalculado", label: "Volumen embalado calculado", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "VolumenEmbaladoAjustado", label: "Volumen embalado ajustado", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "PesoEmbaladoCalculado", label: "Peso embalado calculado", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "PesoEmbaladoAjustado", label: "Peso embalado ajustado", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "NovedadFecha", label: "Novedad fecha", tipo: "string", opciones: "texto", columna: false, habilitado: false },
  { atributo: "EstadoDeEntrega", label: "Estado de entrega", tipo: "boolean", opciones: "texto", columna: false, habilitado: false },
  { atributo: "EstadoDeFacturacion", label: "Estado de facturacion", tipo: "boolean", opciones: "texto", columna: false, habilitado: false },
  { atributo: "NCDeCancelacionesDeAnticipo", label: "Ncde cancelaciones de anticipo", tipo: "string", opciones: "texto", columna: false, habilitado: false },
  { atributo: "HoraDeAprobacion", label: "Hora de aprobacion", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualNombre", label: "Cliente eventual nombre", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualDomicilio", label: "Cliente eventual domicilio", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualLocalidad", label: "Cliente eventual localidad", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualTelefono", label: "Cliente eventual telefono", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualCodigoPostal", label: "Cliente eventual codigo postal", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualProvincia", label: "Cliente eventual provincia", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualCuit", label: "Cliente eventual cuit", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualTipoDeDocumentoDeIdentidad", label: "Cliente eventual tipo de documento de identidad", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualNumeroDeDocumentoDeIdentidad", label: "Cliente eventual numero de documento de identidad", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualMunicipio", label: "Cliente eventual municipio", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualCalle", label: "Cliente eventual calle", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualNumeroCalle", label: "Cliente eventual numero calle", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualDepartamento", label: "Cliente eventual departamento", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualPiso", label: "Cliente eventual piso", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualBarrio", label: "Cliente eventual barrio", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualEmail", label: "Cliente eventual email", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualPais", label: "Cliente eventual pais", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualJurisdiccionDeIngresosBrutosAFIP", label: "Cliente eventual jurisdiccion de ingresos brutos afip", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualDomicilioEntrega", label: "Cliente eventual domicilio entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualLocalidadEntrega", label: "Cliente eventual localidad entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualCodigoPostalEntrega", label: "Cliente eventual codigo postal entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualProvinciaEntrega", label: "Cliente eventual provincia entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualCalleEntrega", label: "Cliente eventual calle entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualNumeroCalleEntrega", label: "Cliente eventual numero calle entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualDepartamentoEntrega", label: "Cliente eventual departamento entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualPisoEntrega", label: "Cliente eventual piso entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },
  { atributo: "ClienteEventualBarrioEntrega", label: "Cliente eventual barrio entrega", tipo: "string", opciones: "texto", columna: true, habilitado: false },];
